[package]
name = "native-runner"
version = "1.0.0"
edition = "2021"
description = "A native runner for the Archytex editor"
authors = ["Guly√°s Arnold"]
default-run = "native-runner"

[dependencies]
winit = "0"
app = { path = "../app" }